server:
  port: 9527
spring:
  application:
    name: springcloud-zuul #微服务名称
  cloud:
    nacos:
      server-addr: localhost:8848
# eureka 注册中心配置
#eureka:
#  client:
#    service-url:
#      defaultZone: 'http://localhost:7001/eureka/'
info:
  app.name: shaw # 项目名称

# zull 路由网关配置
zuul:
  # 路由相关配置
  # 原来访问路由 eg:http://www.cspStudy.com:9527/springcloud-provider-dept/dept/get/1
  # zull路由配置后访问路由 eg:http://www.cspstudy.com:9527/haust/mydept/dept/get/1
  routes:
    mydept.serviceId: deptprovider # eureka注册中心的服务提供方路由名称
#    需要小写
    mydept.path: /mydept/** # 将eureka注册中心的服务提供方路由名称 改为自定义路由名称
  # *： 忽略,隐藏全部的服务名称~ 就不能再使用服务名的路径访问
  ignored-services: "*"
  # 设置公共的前缀
  prefix: /shaw
