server:
  port: 8002
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf8
    username: root
    password: '*strawberry'
  cloud:
    nacos:
      server-addr: localhost:8848
#      discovery:
#        cluster-name: SZ
#Eureka的配置信息
#eureka:
#  instance:
#    instance-id: 'springcoud-provider-8002'
#  client:
#    service-url:
#      defaultZone: 'http://localhost:7001/eureka/'

#配置actuator的info信息
info:
  app.name: "shawjintran"
