server:
  port: 8001
#MyBatis
#感觉是因为微服务,所以需要配置type属性,而mapper-location是因为,没有直接用springboot开始构建项目
mybatis-plus:
  type-aliases-package: com.shaw.springcloud.pojo
  mapper-locations: classpath:/*.xml
spring:
  application:
    name: DeptProvider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf8
    username: root
    password: '*strawberry'
  cloud:
    nacos:
      server-addr: localhost:8848


#Eureka的配置信息
#eureka:
#  instance:
#    instance-id: 'springcoud-provider-8001'
#  client:
#    service-url:
#      defaultZone: 'http://localhost:7001/eureka/'



#配置actuator的info信息
info:
  app.name: "shawjintran"
